image: ubuntu:18.04

before_script:
  - add-apt-repository ppa:cncf-buildpacks/pack-cli
  - apt-get update -y
  - apt-get install pack-cli --no-install -qq

after_script:
  - echo "After script section"
  - echo "For example you might do some cleanup here"

build1:
  stage: build
  script:
    - pack buildpack package futurehax-android-buildpack --config ./package.toml --format file

