api = "0.4"

[buildpack]
id = "kkyger/android-buildpack"
version = "0.0.2"
name = "Android"
homepage = "https://gitlab.futurehax.com/FutureHax/androidbuildpack"
description = "In developmemnt Buildpack for Android applications"
keywords = ["java", "jvm", "jdk", "openjdk", "gradle", "gradlew", "android"]

[[buildpack.licenses]]
type = "BSD-3-Clause"

[[order]]
[[order.group]]
id = "heroku/jvm"
version = "0.1.12"

[[order.group]]
id = "kkyger/android-buildpack"
version = "0.0.2"
